apiVersion: v1
kind: Service
metadata:
  name: wiki
  labels:
    app: wiki
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: wiki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wiki
  name: wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: work-pool
      initContainers:
        - image: 'gcr.io/homin-dev/wikidata:latest'
          name: copy-data
          volumeMounts:
            - name: wiki-data
              mountPath: /data
          command: ["/copy-wikidata.sh"]
          
      containers:
        - image: 'gcr.io/homin-dev/nginx-php:latest'
          name: wiki
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wiki-data
              mountPath: /var/www/html/wiki
        - image: 'gcr.io/homin-dev/php-fpm-wiki:latest'
          name: fpm-wiki-data
          volumeMounts:
            - name: wiki-data
              mountPath: /var/www/html/wiki
      volumes:
        - name: wiki-data
          emptyDir: {}
