<?php
// This file is automatically generated
$gads_settings['code'] = '  <script async src=\"https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9322146642801439\"
     crossorigin=\"anonymous\"></script>';
$gads_settings['dontcountadmin'] = '0';
$gads_settings['dontcountmanager'] = '0';
$gads_settings['dontcountusers'] = '0';
